# Generated by Django 2.0.7 on 2018-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100, verbose_name='工程')),
                ('area', models.CharField(max_length=100, verbose_name='面积')),
            ],
        ),
        migrations.CreateModel(
            name='TableTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100, verbose_name='工程')),
                ('area', models.CharField(max_length=100, verbose_name='面积')),
            ],
        ),
    ]
