# Generated by Django 2.0.7 on 2018-08-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100, verbose_name='产品类型')),
            ],
        ),
        migrations.CreateModel(
            name='TypeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/%Y%M', verbose_name='详情')),
                ('the_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.SystemType', verbose_name='产品类型')),
            ],
        ),
    ]
