# Generated by Django 2.0.7 on 2018-08-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_systemtype_typeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemtype',
            options={'verbose_name': '产品类型', 'verbose_name_plural': '产品类型'},
        ),
        migrations.AlterModelOptions(
            name='tableone',
            options={'verbose_name': '工程1', 'verbose_name_plural': '工程1'},
        ),
        migrations.AlterModelOptions(
            name='tabletwo',
            options={'verbose_name': '工程2', 'verbose_name_plural': '工程2'},
        ),
        migrations.AlterModelOptions(
            name='typeimage',
            options={'verbose_name': '详情', 'verbose_name_plural': '详情'},
        ),
        migrations.AddField(
            model_name='systemtype',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemtype',
            name='types',
            field=models.CharField(default='', max_length=100, verbose_name='产品类型'),
        ),
    ]
